name: TestSysmon

on:
  push:
    paths:
      - '**.xml'
  workflow_dispatch:

jobs:
  test-endpoint:
    runs-on: windows-latest
    steps:
      - id: Checkout
        uses: actions/checkout@v3
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Run test script
        working-directory: "${{ github.workspace }}"
        shell: pwsh
        run: |
          .\.github\workflows\sysmon_test.ps1 -sysmonFile ${{ steps.files.outputs.all }}

